
### Register 
POST http://localhost:5000/user/register
Content-Type: application/json

{
    "username":"lananh",
    "email":"duc1445@gmail.com",
    "password":"duc1445@gmail.com"
}

### Login 
POST http://localhost:5000/user/login
Content-Type: application/json

{
    "email":"duccon303@gmail.com",
    "password":"duccon303@gmail.com"
}

### refresh Token
POST http://localhost:5000/user/refresh_token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMWEwYWU4NmFjZmM0MWQ2OGY5NjM4MSIsIm5hbWUiOiJkdWNkdW9uZyIsImlhdCI6MTYzMDAzNjMzNCwiZXhwIjoxNjMwMTIyNzM0fQ.Qj-whSePDDKsbAFRaLkxqM1fmrxkgRmt7oAjt57ZZJ0"
}



### get AllUser
GET http://localhost:5000/user/all
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMWEwYWU4NmFjZmM0MWQ2OGY5NjM4MSIsIm5hbWUiOiJkdWNkdW9uZyIsImlhdCI6MTYzMDAzNjMzNCwiZXhwIjoxNjMwMDM2MzY0fQ.G8LvZQkxJ19_sv7aIR5w644W1eO-tR9G0whUDL1lyxs